#!/bin/sh

# if committed files do not contain .py files, go ahead and push
git diff-tree --no-commit-id --name-only -r HEAD | grep "\.py$"
if [ $? -ne 0 ]; then
    exit 0
fi
python -m unittest discover -s tests/classes

# abort push if test fails
if [ $? -eq 0 ]; then
    exit 0
else
    exit 1
fi