#!/bin/sh

# if committed files do not contain .py files, go ahead and push
git diff-tree --no-commit-id --name-only -r HEAD | grep "\.py$"
if [ $? -n 0]; then
    exit 0
fi
python -m unittest discover -s tests/classes

# abort push if test fails
if [ $? -n 0]; then
    exit 0
else
    exit 1
fi